server:
   port: 3000

tomcat:
   ajp:
      port: 8009

spring:
  security:
    oauth2:
      client:
        registration:
         naver:
            client-id: A43Bves_ovKKl8L3XGjM
            client-secret: xFhNIDQs5Y
            redirect-uri: "http://localhost:3000/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
         kakao:
            client-id: a63045f6b604e2400c49ec1fff9bc91e
            client-secret: ""
            redirect-uri: "http://localhost:3000/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email
            client-name: Kakao
         facebook:
            client-id: 220208929975498
            client-secret: e884b23b1b9ba592149ad81d059345c2
            redirect-uri: "http://localhost:3000/login/oauth2/code/facebook"
         google:
            client-id: 61294626708-i6363305oiiab2hlhobuqcqblurrubsm.apps.googleusercontent.com
            client-secret: W3Pr6Ij8OLQRjtZcrb62orqn
            redirect-uri: "http://localhost:3000/login/oauth2/code/google"
            scope: profile,email
            client-name: Google
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            
# Metrics
management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    health:
      show-details: always